name = "Better Content"
version = "Playtest 4 - v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e97c33f11a731431729f5640c736a6da44c595c3b8e507884ffbd0afef7dd290"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["list"]
