name = "Better Content — Persistence Playtest"
version = "Build 40"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "384e7113e441c1f6f1a15160b88e104c760916dde715f4012f7f61034d7d9660"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["list"]
