name = "Better Content Modpack"
version = "Build 183"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "007835de4405e49fc46ef6be0eebdc8b2440564ae2d5cbec3511ccddf9bf2d7e"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["list"]
