name = "Better Content Modpack"
version = "Build 198"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d5c673c4538f5021f9ced8d06db4d71c51c14b6e1be7606206bfe778fd67c10"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["list"]
