#A list of block IDs and tags that should be affected by this definition.
#Entries can be supplied in the below formats:
#	Namespaces:   '<minecraft>'
#	Tags:         '#forge:stone'
#	IDs:          'minecraft:stone'
Blocks = [
	"adpother:dust",
	"blue_skies:chiseled_crystal_sandstone",
	"blue_skies:chiseled_midnight_sandstone",
	"blue_skies:coarse_lunar_dirt",
	"blue_skies:coarse_turquoise_dirt",
	"blue_skies:crystal_sand",
	"blue_skies:crystal_sandstone",
	"blue_skies:crystal_sandstone_pillar",
	"blue_skies:crystal_sandstone_slab",
	"blue_skies:crystal_sandstone_stairs",
	"blue_skies:crystal_sandstone_wall",
	"blue_skies:cut_crystal_sandstone",
	"blue_skies:cut_crystal_sandstone_slab",
	"blue_skies:cut_midnight_sandstone",
	"blue_skies:cut_midnight_sandstone_slab",
	"blue_skies:lunar_comet_grass_block",
	"blue_skies:lunar_dirt",
	"blue_skies:lunar_grass_block",
	"blue_skies:lunar_mud",
	"blue_skies:midnight_sand",
	"blue_skies:midnight_sandstone",
	"blue_skies:midnight_sandstone_pillar",
	"blue_skies:midnight_sandstone_slab",
	"blue_skies:midnight_sandstone_stairs",
	"blue_skies:midnight_sandstone_wall",
	"blue_skies:smooth_crystal_sandstone",
	"blue_skies:smooth_crystal_sandstone_slab",
	"blue_skies:smooth_crystal_sandstone_stairs",
	"blue_skies:smooth_midnight_sandstone",
	"blue_skies:smooth_midnight_sandstone_slab",
	"blue_skies:smooth_midnight_sandstone_stairs",
	"blue_skies:turquoise_comet_grass_block",
	"blue_skies:turquoise_dirt",
	"blue_skies:turquoise_grass_block",
	"better_content_fixes:burnt_aether_grass_block",
	"better_content_fixes:burnt_beige_limestone_grassy_regolith",
	"better_content_fixes:burnt_chorus_grass_block",
	"better_content_fixes:burnt_conglomerate_grassy_regolith",
	"better_content_fixes:burnt_dolomite_grassy_regolith",
	"better_content_fixes:burnt_enchanted_aether_grass_block",
	"better_content_fixes:burnt_finley_grass_block",
	"better_content_fixes:burnt_gabbro_grassy_regolith",
	"better_content_fixes:burnt_granodiorite_grassy_regolith",
	"better_content_fixes:burnt_grassy_permafrost",
	"better_content_fixes:burnt_grassy_silt",
	"better_content_fixes:burnt_grey_limestone_grassy_regolith",
	"better_content_fixes:burnt_kimberlite_grassy_regolith",
	"better_content_fixes:burnt_limestone_grassy_regolith",
	"better_content_fixes:burnt_living_grass_block",
	"better_content_fixes:burnt_lunar_comet_grass_block",
	"better_content_fixes:burnt_lunar_grass_block",
	"better_content_fixes:burnt_mudstone_grassy_regolith",
	"better_content_fixes:burnt_phyllite_grassy_regolith",
	"better_content_fixes:burnt_quartzite_grassy_regolith",
	"better_content_fixes:burnt_rhyolite_grassy_regolith",
	"better_content_fixes:burnt_rooted_grass_block",
	"better_content_fixes:burnt_rooty_aether_grass_block",
	"better_content_fixes:burnt_rooty_enchanted_aether_grass_block",
	"better_content_fixes:burnt_rooty_frozen_aether_grass_block",
	"better_content_fixes:burnt_rooty_grass_block",
	"better_content_fixes:burnt_sandstone_grassy_regolith",
	"better_content_fixes:burnt_siltstone_grassy_regolith",
	"better_content_fixes:burnt_slate_grassy_regolith",
	"better_content_fixes:burnt_stone_grassy_regolith",
	"better_content_fixes:burnt_turquoise_comet_grass_block",
	"better_content_fixes:burnt_turquoise_grass_block",
	"better_content_fixes:burnt_white_granite_grassy_regolith",
	"buildinggadgets2:construction_block_powder",
	"burnt:burnt_grassy_earthen_clay",
	"burnt:burnt_grassy_sandy_d_irt",
	"creatingspace:mars_regolith",
	"creatingspace:mars_surface_regolith",
	"creatingspace:moon_regolith",
	"creatingspace:moon_surface_regolith",
	"everythingcopper:copper_powder_snow_cauldron",
	"everythingcopper:exposed_copper_powder_snow_cauldron",
	"everythingcopper:oxidized_copper_powder_snow_cauldron",
	"everythingcopper:waxed_copper_powder_snow_cauldron",
	"everythingcopper:waxed_exposed_copper_powder_snow_cauldron",
	"everythingcopper:waxed_oxidized_copper_powder_snow_cauldron",
	"everythingcopper:waxed_weathered_copper_powder_snow_cauldron",
	"everythingcopper:weathered_copper_powder_snow_cauldron",
	"excavated_variants:red_sandstone_brilliant_stone",
	"excavated_variants:red_sandstone_cantazarite_ore",
	"excavated_variants:red_sandstone_coal_measures",
	"excavated_variants:red_sandstone_copper_bloom",
	"excavated_variants:red_sandstone_gem_pipe",
	"excavated_variants:red_sandstone_cthonic_gold_ore",
	"excavated_variants:red_sandstone_redbed",
	"excavated_variants:red_sandstone_darkstone",
	"excavated_variants:red_sandstone_gilded_darkstone",
	"excavated_variants:red_sandstone_ironstone",
	"excavated_variants:red_sandstone_jade_ore",
	"excavated_variants:red_sandstone_brassroot",
	"excavated_variants:red_sandstone_natural_quartz_ore",
	"excavated_variants:red_sandstone_hotstone",
	"excavated_variants:red_sandstone_evaporite_beds",
	"excavated_variants:red_sandstone_tin_quartz",
	"excavated_variants:red_sandstone_runic_stone",
	"excavated_variants:red_sandstone_black_shale",
	"excavated_variants:red_sandstone_soulstone_ore",
	"excavated_variants:red_sandstone_stella_arcanum",
	"excavated_variants:red_sandstone_tin",
	"excavated_variants:red_sandstone_xpetrified_ore",
	"excavated_variants:red_sandstone_zinc",
	"excavated_variants:sandstone_brilliant_stone",
	"excavated_variants:sandstone_cantazarite_ore",
	"excavated_variants:sandstone_coal_measures",
	"excavated_variants:sandstone_copper_bloom",
	"excavated_variants:sandstone_gem_pipe",
	"excavated_variants:sandstone_cthonic_gold_ore",
	"excavated_variants:sandstone_redbed",
	"excavated_variants:sandstone_darkstone",
	"excavated_variants:sandstone_gilded_darkstone",
	"excavated_variants:sandstone_ironstone",
	"excavated_variants:sandstone_jade_ore",
	"excavated_variants:sandstone_brassroot",
	"excavated_variants:sandstone_natural_quartz_ore",
	"excavated_variants:sandstone_hotstone",
	"excavated_variants:sandstone_evaporite_beds",
	"excavated_variants:sandstone_tin_quartz",
	"excavated_variants:sandstone_runic_stone",
	"excavated_variants:sandstone_black_shale",
	"excavated_variants:sandstone_soulstone_ore",
	"excavated_variants:sandstone_stella_arcanum",
	"excavated_variants:sandstone_tin",
	"excavated_variants:sandstone_xpetrified_ore",
	"excavated_variants:sandstone_zinc",
	"excavated_variants:unearthed_mudstone_brilliant_stone",
	"excavated_variants:unearthed_mudstone_cantazarite_ore",
	"excavated_variants:unearthed_mudstone_coal_measures",
	"excavated_variants:unearthed_mudstone_copper_bloom",
	"excavated_variants:unearthed_mudstone_gem_pipe",
	"excavated_variants:unearthed_mudstone_cthonic_gold_ore",
	"excavated_variants:unearthed_mudstone_redbed",
	"excavated_variants:unearthed_mudstone_darkstone",
	"excavated_variants:unearthed_mudstone_gilded_darkstone",
	"excavated_variants:unearthed_mudstone_ironstone",
	"excavated_variants:unearthed_mudstone_jade_ore",
	"excavated_variants:unearthed_mudstone_brassroot",
	"excavated_variants:unearthed_mudstone_natural_quartz_ore",
	"excavated_variants:unearthed_mudstone_hotstone",
	"excavated_variants:unearthed_mudstone_evaporite_beds",
	"excavated_variants:unearthed_mudstone_tin_quartz",
	"excavated_variants:unearthed_mudstone_runic_stone",
	"excavated_variants:unearthed_mudstone_black_shale",
	"excavated_variants:unearthed_mudstone_soulstone_ore",
	"excavated_variants:unearthed_mudstone_stella_arcanum",
	"excavated_variants:unearthed_mudstone_tin",
	"excavated_variants:unearthed_mudstone_xpetrified_ore",
	"excavated_variants:unearthed_mudstone_zinc",
	"excavated_variants:unearthed_siltstone_brilliant_stone",
	"excavated_variants:unearthed_siltstone_cantazarite_ore",
	"excavated_variants:unearthed_siltstone_coal_measures",
	"excavated_variants:unearthed_siltstone_copper_bloom",
	"excavated_variants:unearthed_siltstone_gem_pipe",
	"excavated_variants:unearthed_siltstone_cthonic_gold_ore",
	"excavated_variants:unearthed_siltstone_redbed",
	"excavated_variants:unearthed_siltstone_darkstone",
	"excavated_variants:unearthed_siltstone_gilded_darkstone",
	"excavated_variants:unearthed_siltstone_ironstone",
	"excavated_variants:unearthed_siltstone_jade_ore",
	"excavated_variants:unearthed_siltstone_brassroot",
	"excavated_variants:unearthed_siltstone_natural_quartz_ore",
	"excavated_variants:unearthed_siltstone_hotstone",
	"excavated_variants:unearthed_siltstone_evaporite_beds",
	"excavated_variants:unearthed_siltstone_tin_quartz",
	"excavated_variants:unearthed_siltstone_runic_stone",
	"excavated_variants:unearthed_siltstone_black_shale",
	"excavated_variants:unearthed_siltstone_soulstone_ore",
	"excavated_variants:unearthed_siltstone_stella_arcanum",
	"excavated_variants:unearthed_siltstone_tin",
	"excavated_variants:unearthed_siltstone_xpetrified_ore",
	"excavated_variants:unearthed_siltstone_zinc",
	"fallout_wastelands_:rockydirt",
	"fallout_wastelands_:sandbags",
	"fallout_wastelands_:sandbagstairs",
	"fallout_wastelands_:wasteland_sand_stone",
	"fallout_wastelands_:wastelanddrydirt",
	"forbidden_arcanus:cut_soulless_sandstone",
	"forbidden_arcanus:cut_soulless_sandstone_slab",
	"forbidden_arcanus:polished_soulless_sandstone",
	"forbidden_arcanus:polished_soulless_sandstone_slab",
	"forbidden_arcanus:polished_soulless_sandstone_stairs",
	"forbidden_arcanus:soulless_sand",
	"forbidden_arcanus:soulless_sandstone",
	"forbidden_arcanus:soulless_sandstone_slab",
	"forbidden_arcanus:soulless_sandstone_stairs",
	"forbidden_arcanus:soulless_sandstone_wall",
	"goety:blue_siltstone_pillar",
	"goety:bottom_soiled_end_basalt",
	"goety:chiseled_siltstone",
	"goety:chiseled_siltstone_bricks",
	"goety:chorus_grass_block",
	"goety:chorus_grass_block_slab",
	"goety:cobbled_chorus_grass_block",
	"goety:cobbled_siltstone",
	"goety:cobbled_siltstone_slab",
	"goety:cobbled_siltstone_stairs",
	"goety:cobbled_siltstone_wall",
	"goety:dark_dirt_slab",
	"goety:dirty_chiseled_siltstone",
	"goety:dirty_cobbled_end_stone",
	"goety:dirty_cobbled_end_stone_heavy",
	"goety:dirty_cobbled_siltstone",
	"goety:dirty_end_basalt",
	"goety:dirty_end_rock",
	"goety:dirty_ominous_stone",
	"goety:dirty_ominous_stone_bricks",
	"goety:dirty_ominous_stone_bricks_heavy",
	"goety:dirty_ominous_stone_bricks_slight",
	"goety:dirty_ominous_stone_pavement",
	"goety:dirty_ominous_stone_pavement_heavy",
	"goety:dirty_ominous_stone_slight",
	"goety:dirty_ominous_stone_tiles",
	"goety:dirty_ominous_stone_tiles_heavy",
	"goety:dirty_ominous_stone_tiles_slight",
	"goety:dirty_siltstone",
	"goety:dirty_siltstone_heavy",
	"goety:end_dirt",
	"goety:end_dirt_slab",
	"goety:end_mud",
	"goety:end_mud_cauldron",
	"goety:end_mud_fluid",
	"goety:end_mud_slab",
	"goety:end_soil",
	"goety:end_soil_debris",
	"goety:grassy_cobbled_end_stone",
	"goety:grassy_end_basalt",
	"goety:grassy_end_rock",
	"goety:grassy_end_rock_bricks",
	"goety:grassy_end_stone_bricks",
	"goety:grassy_end_stone_bricks_heavy",
	"goety:grassy_end_stone_tiles",
	"goety:grassy_purpur_block",
	"goety:grassy_smooth_end_stone",
	"goety:grassy_smooth_end_stone_heavy",
	"goety:green_siltstone_pillar",
	"goety:muddy_smooth_end_stone",
	"goety:red_siltstone_pillar",
	"goety:silt_highrock",
	"goety:silt_highrock_slab",
	"goety:silt_jade_slab",
	"goety:silt_jade_stairs",
	"goety:silt_jade_tiles",
	"goety:silt_marble",
	"goety:silt_marble_heavy",
	"goety:silt_marble_slight",
	"goety:silt_slate_marble",
	"goety:silt_studded_crag_tiles",
	"goety:siltstone",
	"goety:siltstone_brick_slab",
	"goety:siltstone_brick_stairs",
	"goety:siltstone_brick_wall",
	"goety:siltstone_bricks",
	"goety:siltstone_pavement",
	"goety:siltstone_pavement_slab",
	"goety:siltstone_pavement_stairs",
	"goety:siltstone_pavement_wall",
	"goety:siltstone_pillar",
	"goety:siltstone_slab",
	"goety:siltstone_stairs",
	"goety:siltstone_tile_slab",
	"goety:siltstone_tile_stairs",
	"goety:siltstone_tile_wall",
	"goety:siltstone_tiles",
	"goety:siltstone_wall",
	"goety:smooth_siltstone",
	"goety:smooth_siltstone_slab",
	"goety:smooth_siltstone_stairs",
	"goety:smooth_siltstone_wall",
	"goety:snowy_chiseled_siltstone",
	"goety:snowy_cobbled_siltstone",
	"goety:snowy_cobbled_siltstone_slab",
	"goety:snowy_cobbled_siltstone_stairs",
	"goety:snowy_cobbled_siltstone_wall",
	"goety:snowy_siltstone",
	"goety:snowy_siltstone_brick_slab",
	"goety:snowy_siltstone_brick_slight_slab",
	"goety:snowy_siltstone_brick_slight_stairs",
	"goety:snowy_siltstone_brick_slight_wall",
	"goety:snowy_siltstone_brick_stairs",
	"goety:snowy_siltstone_brick_wall",
	"goety:snowy_siltstone_bricks",
	"goety:snowy_siltstone_bricks_slight",
	"goety:snowy_siltstone_pillar",
	"goety:snowy_siltstone_slight",
	"goety:soiled_cobbled_end_stone",
	"goety:soiled_cobbled_end_stone_heavy",
	"goety:soiled_cobbled_end_stone_slight",
	"goety:soiled_end_basalt",
	"goety:soiled_end_basalt_bricks",
	"goety:soiled_end_basalt_slight",
	"goety:soiled_end_dirt",
	"goety:soiled_end_rock",
	"goety:soiled_end_rock_bricks",
	"goety:soiled_end_rock_chiseled",
	"goety:soiled_end_stone_bricks",
	"goety:soiled_end_stone_bricks_heavy",
	"goety:soiled_end_stone_bricks_slight",
	"goety:soiled_end_stone_tiles",
	"goety:soiled_polished_ominous_stone",
	"goety:soiled_polished_ominous_stone_heavy",
	"goety:soiled_purpur_block",
	"goety:top_soiled_end_basalt",
	"immersive_weathering:red_sand_layer_block",
	"immersive_weathering:sand_layer_block",
	"immersive_weathering:sandy_chiseled_stone_bricks",
	"immersive_weathering:sandy_cobblestone",
	"immersive_weathering:sandy_stone",
	"immersive_weathering:sandy_stone_bricks",
	"immersive_weathering:vitrified_sand",
	"natures_spirit:chiseled_pink_sandstone",
	"natures_spirit:cut_pink_sandstone",
	"natures_spirit:pink_sandstone",
	"natures_spirit:smooth_pink_sandstone",
	"notreepunching:red_sandstone_loose_rock",
	"notreepunching:sandstone_loose_rock",
	"projectvibrantjourneys:ferrous_gravel",
	"projectvibrantjourneys:gilded_gravel",
	"projectvibrantjourneys:muddy_bones",
	"projectvibrantjourneys:red_sandstone_rocks",
	"projectvibrantjourneys:sandstone_rocks",
	"projectvibrantjourneys:sandy_sprouts",
	"quark:chiseled_soul_sandstone",
	"quark:cut_soul_sandstone",
	"quark:gravisand",
	"quark:red_sandstone_bricks",
	"quark:sandstone_bricks",
	"quark:smooth_soul_sandstone",
	"quark:soul_sandstone",
	"quark:soul_sandstone_bricks",
	"swem:soiled_shavings",
	"the_flesh_that_hates:flesh_sand",
	"thirst:sand_filter",
	"undergarden:sediment",
	"unearthed:chiseled_mudstone",
	"unearthed:chiseled_siltstone",
	"unearthed:cut_mudstone",
	"unearthed:cut_siltstone",
	"unearthed:smooth_siltstone",
	"weather2:sand_layer",
]

[Physics]
	#The maximum weight the block(s) can support both horizontally and vertically.
	#Range: > 0
	SupportStrength = 0

	#Additional support strength to apply to the amount of weight the block(s) can support above when acting as a beam.
	#A value of 1.0 will allow the block(s) to support an infinite amount of weight, whereas a value of 0.0 will not apply any additional strengthening.
	#Range: 0.0 ~ 1.0
	BeamStrength = 0.9

	#The mass of the block(s), in kilograms.
	#Range: 1.0 ~ 50000.0
	Mass = 650.0

	#Whether the block(s) can hang from other blocks for support.
	CanHang = false

	#Whether the block(s) can attach to the sides of other blocks for support.
	CanAttach = false

	#Whether the block(s) can diagonally attach to other blocks for support.
	CanAttachDiagonally = true

	#The chance the block(s) will slide after falling and landing.
	#Range: 0.0 ~ 1.0
	SlideChance = 0.5

	#An additional "dice roll" to apply to the base slide chance of the block(s), when being placed by an entity.
	#Setting a value of 1.0 means the slide chance will remain unaffected.
	#Range: 0.0 ~ 1.0
	PlacementSlideModifier = 0.0

	#A multiplier to apply to the damage caused by the block(s) when falling on entities.
	#Range: 0.0 ~ 10.0
	EntityDamageScale = 1.0

	#Whether the block(s) should break instead of falling.
	BreaksOnFalling = false

	#The maximum force the block(s) can withstand before being broken.
	#Range: > 0
	Strength = 195600

	#Whether the block(s) can be supported by liquids that are below.
	FloatsOnLiquid = false

	#This section allows you to extend the collision bounds for each specific face of the block(s).
	#Note: Directions are relative to the orientation of the block(s) (excluding vertical axis), not the world itself.
	[Physics.ExtendedCollisionBounds]
		#Fully extends the collision bounds of the block(s) in the UP direction.
		Up = false

		#Fully extends the collision bounds of the block(s) in the DOWN direction.
		Down = false

		#Fully extends the collision bounds of the block(s) in the NORTH direction.
		North = false

		#Fully extends the collision bounds of the block(s) in the EAST direction.
		East = false

		#Fully extends the collision bounds of the block(s) in the SOUTH direction.
		South = false

		#Fully extends the collision bounds of the block(s) in the WEST direction.
		West = false

[ChunkAnalysis]
	#Whether the block(s) should be processed during chunk analysis updates.
	Enabled = true
