allow-flight=true
difficulty=normal
enable-command-block=false
level-name=world
level-type=minecraft\:normal
max-players=20
online-mode=true
server-ip=
server-port=25565
spawn-protection=16
view-distance=10
simulation-distance=10
